[app]
app_server ansible_host=100.61.117.138 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/awskey

[db]
db_server ansible_host=75.101.250.192 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/awskey

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
ansible_python_interpreter=/usr/bin/python3
db_name=cotisations_db
db_user=ucad_user
db_password=SecretUcadPassword2026!
db_private_ip=10.0.1.42